title: Lightweight Modular Staging
tagline: Program Generation and Embedded Compilers in Scala
github_url: https://github.com/TiarkRompf/virtualization-lms-core

production_url : https://scala-lms.github.io
baseurl: 

 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-primer
 gfm_quirks: paragraph_end

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge