#auto: true
highlighter: rouge
markdown: kramdown

title: Lightweight Modular Staging
tagline: Program Generation and Embedded Compilers in Scala
github_url: https://github.com/TiarkRompf/virtualization-lms-core

production_url : https://scala-lms.github.io
baseurl: 

